In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# import numpy

In [4]:
import numpy as np

## creating array

In [5]:
numList = [5,1,3]

In [13]:
floatList = [5.3,1.1,3.4]

In [6]:
textList = ['sahil', 'harjeet', 'ujwal']

In [7]:
boolList = [True,False,True]

In [8]:
numArr = np.array(numList)

In [9]:
print(numArr)

[5 1 3]


In [10]:
numArr

array([5, 1, 3])

In [14]:
floatArr = np.array(floatList)

In [15]:
floatArr.dtype

dtype('float64')

In [16]:
floatArr

array([5.3, 1.1, 3.4])

In [17]:
print(floatArr)

[5.3 1.1 3.4]


In [18]:
textArr = np.array(textList)

In [19]:
textArr

array(['sahil', 'harjeet', 'ujwal'], dtype='<U7')

In [20]:
textArr.dtype

dtype('<U7')

In [21]:
boolArr = np.array(boolList)

In [22]:
boolArr

array([ True, False,  True])

In [23]:
boolArr.dtype

dtype('bool')

In [25]:
boolArr.dtype

dtype('bool')

In [26]:
print(boolArr)

[ True False  True]


In [27]:
np.array([5,6.3,True, "sahil"])

array(['5', '6.3', 'True', 'sahil'], dtype='<U32')

In [39]:
Arr = np.array( [8,6,2,4,17,20,4,8,5,6] )

In [40]:
Arr

array([ 8,  6,  2,  4, 17, 20,  4,  8,  5,  6])

In [41]:
Arr.shape   # total item btayega

(10,)

In [50]:
Arr.ndim # no. of bracket

1

In [51]:
Arr.size

10

## scaler

In [43]:
scaler = np.array(5)

In [44]:
scaler

array(5)

In [45]:
print(scaler)

5


In [46]:
scaler.dtype

dtype('int64')

In [47]:
scaler.shape

()

In [48]:
scaler.size

1

In [49]:
scaler.ndim

0

### vector

In [52]:
vector = np.array([5,2,3,5])

In [53]:
vector

array([5, 2, 3, 5])

In [54]:
print(vector)

[5 2 3 5]


In [55]:
vector.ndim

1

In [56]:
vector.size

4

In [59]:
vector.shape

(4,)

## MATRIX
### matrix is collection of lot of vector

In [61]:
matrix = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [62]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
matrix.shape

(3, 3)

In [67]:
matrix.size

9

In [68]:
matrix.ndim

2

In [71]:
matrix = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)

In [72]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
matrix.shape

(3, 4)

In [76]:
matrix.size

12

In [77]:
matrix.ndim

2

## TENSOR 
### it is multidimensional array

In [81]:
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ],
    
   [ 
        [9,10],
        [11,12]
    ]
])

In [82]:
tensor.size

12

In [83]:
tensor.shape

(3, 2, 2)

In [84]:
tensor.ndim

3

## RESHAPE
#### reshape is used to change the shape (rows , columns , dimensions) of array without changing data

In [108]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [109]:
array

[2, 3, 4, 6, 4, 2, 7, 3]

In [110]:
arr.size

12

In [111]:
arr.shape

(12,)

In [112]:
arr.dtype

dtype('int64')

In [113]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [114]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [116]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [5]:
arr = np.array([x for x in range(1,25)])

In [118]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [120]:
arr.shape

(24,)

In [121]:
arr.size

24

In [122]:
arr.ndim

1

In [123]:
arr.reshape(4,-1)   # -1 apne app baki ki shape lga leta h

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [124]:
arr.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [6]:
arr.reshape(2,3,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [7]:
arr.reshape(8,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [8]:
arr.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

 ## basic 02

##### making 1D

In [3]:
import numpy as np

In [11]:
array = np.array([1,2,3,4])

In [37]:
array

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [12]:
array.shape

(4,)

In [13]:
array.ndim

1

##### making 2D

In [15]:
array =np.array ([[1,2,3], [1,2,3] , [1,2,3]])

In [38]:
array

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [16]:
array.shape

(3, 3)

In [17]:
array.ndim

2

In [18]:
array = np.array([[1,2,3], [1,2,3]])

In [39]:
array

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [19]:
array.shape

(2, 3)

In [20]:
array.ndim

2

##### making 3D

In [23]:
array = np.array ([[[1,2,3] , [1,2,3]] , [[1,2,3] , [1,2,3]]])

In [24]:
array.shape

(2, 2, 3)

In [25]:
array

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [26]:
array.ndim

3

 ##### making shape 4,1,3  4 block/layers , 1 row , 3 is column

In [34]:
array = np.array([[[1,2,3]],[[1,2,3]],[[1,2,3]],[[1,2,3]]])

In [35]:
array

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [36]:
array.shape

(4, 1, 3)