In [1]:
import numpy as np

In [6]:
##### seed function helps to more than 1 person to put same data

In [2]:
np.random.seed(50)

In [4]:
arr = np.random.randint(1,20,(3,3))

In [5]:
arr

array([[14,  6,  3],
       [ 8, 16,  5],
       [15,  4,  7]], dtype=int32)

#### INDEXING

In [7]:
arr[2]

array([15,  4,  7], dtype=int32)

In [10]:
arr[2][0]

np.int32(15)

In [12]:
arr[2,0]

np.int32(15)

In [13]:
arr = np.random.randint(1,20,(3,5,4))

In [14]:
arr

array([[[12, 18, 11, 10],
        [ 1,  7,  3, 16],
        [10,  4,  3, 13],
        [ 1,  4,  3, 11],
        [17, 15,  1,  1]],

       [[12,  8, 15, 14],
        [ 8,  5,  5,  1],
        [12,  1, 14, 14],
        [ 2, 10, 12,  6],
        [ 1, 16,  6,  7]],

       [[ 2,  5,  5, 13],
        [15,  5, 12,  1],
        [ 6,  9, 13, 12],
        [ 4,  7, 19,  9],
        [16,  6, 16,  5]]], dtype=int32)

In [15]:
arr[1]

array([[12,  8, 15, 14],
       [ 8,  5,  5,  1],
       [12,  1, 14, 14],
       [ 2, 10, 12,  6],
       [ 1, 16,  6,  7]], dtype=int32)

In [16]:
arr[0]

array([[12, 18, 11, 10],
       [ 1,  7,  3, 16],
       [10,  4,  3, 13],
       [ 1,  4,  3, 11],
       [17, 15,  1,  1]], dtype=int32)

In [17]:
arr[1,3]

array([ 2, 10, 12,  6], dtype=int32)

In [18]:
arr[1,3,3]

np.int32(6)

#### SLICING

In [21]:
arr = np.random.randint(1,20,(5,5))

In [20]:
arr

array([[ 5, 19, 16, 11, 18],
       [ 9, 15, 12,  8, 10],
       [ 2,  9,  4,  4, 11],
       [ 4,  7, 16,  1, 19],
       [12,  2, 18, 15, 15]], dtype=int32)

In [24]:
arr[2:4, 1:3]

array([[12,  2],
       [15,  3]], dtype=int32)

In [25]:
arr = np.random.randint(1,20,(3,5,4))

In [26]:
arr

array([[[15,  5, 12, 17],
        [18, 15, 16,  4],
        [ 5, 10,  5,  8],
        [18, 14, 10, 15],
        [14, 16,  4,  7]],

       [[13, 11, 15,  1],
        [14, 14,  1,  9],
        [16, 14,  1, 11],
        [15, 13,  5,  9],
        [11, 11,  1,  8]],

       [[ 5, 12, 14,  1],
        [ 9, 16,  7,  4],
        [ 6, 12, 19,  2],
        [16,  4,  4,  1],
        [15, 11, 13,  6]]], dtype=int32)

In [27]:
arr[2]

array([[ 5, 12, 14,  1],
       [ 9, 16,  7,  4],
       [ 6, 12, 19,  2],
       [16,  4,  4,  1],
       [15, 11, 13,  6]], dtype=int32)

In [28]:
arr[2,2:]

array([[ 6, 12, 19,  2],
       [16,  4,  4,  1],
       [15, 11, 13,  6]], dtype=int32)

In [31]:
arr[2,2:,0:2]

array([[ 6, 12],
       [16,  4],
       [15, 11]], dtype=int32)

In [33]:
arr

array([[[15,  5, 12, 17],
        [18, 15, 16,  4],
        [ 5, 10,  5,  8],
        [18, 14, 10, 15],
        [14, 16,  4,  7]],

       [[13, 11, 15,  1],
        [14, 14,  1,  9],
        [16, 14,  1, 11],
        [15, 13,  5,  9],
        [11, 11,  1,  8]],

       [[ 5, 12, 14,  1],
        [ 9, 16,  7,  4],
        [ 6, 12, 19,  2],
        [16,  4,  4,  1],
        [15, 11, 13,  6]]], dtype=int32)

In [34]:
arr[2,-1,-2]  ## for getting 13 no. in last row and last column

np.int32(13)

In [35]:
arr

array([[[15,  5, 12, 17],
        [18, 15, 16,  4],
        [ 5, 10,  5,  8],
        [18, 14, 10, 15],
        [14, 16,  4,  7]],

       [[13, 11, 15,  1],
        [14, 14,  1,  9],
        [16, 14,  1, 11],
        [15, 13,  5,  9],
        [11, 11,  1,  8]],

       [[ 5, 12, 14,  1],
        [ 9, 16,  7,  4],
        [ 6, 12, 19,  2],
        [16,  4,  4,  1],
        [15, 11, 13,  6]]], dtype=int32)

In [36]:
arr[1,3,-2]

np.int32(5)

In [37]:
arr = np.random.randint(1,25,(5,6,3))

In [38]:
arr

array([[[13,  1, 24],
        [22, 22, 12],
        [15, 20, 14],
        [17,  2, 20],
        [23, 16, 19],
        [12,  1,  5]],

       [[19, 14, 10],
        [16, 18, 19],
        [18, 23,  3],
        [ 6,  2,  2],
        [11, 19, 23],
        [ 9, 15, 18]],

       [[16,  2, 24],
        [10,  8, 23],
        [22, 10, 21],
        [20, 20, 24],
        [15,  5,  6],
        [ 1,  8,  8]],

       [[24, 17, 18],
        [ 3, 11, 10],
        [ 7, 10,  6],
        [14, 21, 19],
        [13, 20,  6],
        [11,  6, 19]],

       [[16, 14, 22],
        [ 8,  7,  1],
        [12, 17,  8],
        [11, 15,  8],
        [20,  4, 19],
        [11, 23, 14]]], dtype=int32)

In [39]:
arr[2,3,-1]

np.int32(24)

In [40]:
arr

array([[[13,  1, 24],
        [22, 22, 12],
        [15, 20, 14],
        [17,  2, 20],
        [23, 16, 19],
        [12,  1,  5]],

       [[19, 14, 10],
        [16, 18, 19],
        [18, 23,  3],
        [ 6,  2,  2],
        [11, 19, 23],
        [ 9, 15, 18]],

       [[16,  2, 24],
        [10,  8, 23],
        [22, 10, 21],
        [20, 20, 24],
        [15,  5,  6],
        [ 1,  8,  8]],

       [[24, 17, 18],
        [ 3, 11, 10],
        [ 7, 10,  6],
        [14, 21, 19],
        [13, 20,  6],
        [11,  6, 19]],

       [[16, 14, 22],
        [ 8,  7,  1],
        [12, 17,  8],
        [11, 15,  8],
        [20,  4, 19],
        [11, 23, 14]]], dtype=int32)

In [41]:
arr[3]

array([[24, 17, 18],
       [ 3, 11, 10],
       [ 7, 10,  6],
       [14, 21, 19],
       [13, 20,  6],
       [11,  6, 19]], dtype=int32)

In [43]:
arr[3,3]

array([14, 21, 19], dtype=int32)

In [44]:
arr[3,3,1]

np.int32(21)

In [45]:
arr

array([[[13,  1, 24],
        [22, 22, 12],
        [15, 20, 14],
        [17,  2, 20],
        [23, 16, 19],
        [12,  1,  5]],

       [[19, 14, 10],
        [16, 18, 19],
        [18, 23,  3],
        [ 6,  2,  2],
        [11, 19, 23],
        [ 9, 15, 18]],

       [[16,  2, 24],
        [10,  8, 23],
        [22, 10, 21],
        [20, 20, 24],
        [15,  5,  6],
        [ 1,  8,  8]],

       [[24, 17, 18],
        [ 3, 11, 10],
        [ 7, 10,  6],
        [14, 21, 19],
        [13, 20,  6],
        [11,  6, 19]],

       [[16, 14, 22],
        [ 8,  7,  1],
        [12, 17,  8],
        [11, 15,  8],
        [20,  4, 19],
        [11, 23, 14]]], dtype=int32)

In [46]:
arr[3]

array([[24, 17, 18],
       [ 3, 11, 10],
       [ 7, 10,  6],
       [14, 21, 19],
       [13, 20,  6],
       [11,  6, 19]], dtype=int32)

In [47]:
arr[3,2]

array([ 7, 10,  6], dtype=int32)

In [49]:
arr[3,2,0]

np.int32(7)

In [50]:
arr[3,2,0] = 18

In [51]:
arr[3]

array([[24, 17, 18],
       [ 3, 11, 10],
       [18, 10,  6],
       [14, 21, 19],
       [13, 20,  6],
       [11,  6, 19]], dtype=int32)

In [52]:
arr = np.random.randint(1,20,(3,5,4))

In [53]:
arr

array([[[16,  1, 14,  1],
        [11, 18,  1,  5],
        [ 2,  5, 15,  5],
        [10, 14, 19, 15],
        [19, 16,  3, 14]],

       [[18,  8,  6, 10],
        [ 8,  9, 18, 16],
        [12,  5, 13, 19],
        [19, 11,  6,  1],
        [14, 17,  2,  9]],

       [[ 4,  4, 11,  1],
        [19, 10, 16, 11],
        [10,  7, 15,  2],
        [ 7, 16,  1,  1],
        [ 4,  2, 18, 16]]], dtype=int32)

In [55]:
arr[1:]

array([[[18,  8,  6, 10],
        [ 8,  9, 18, 16],
        [12,  5, 13, 19],
        [19, 11,  6,  1],
        [14, 17,  2,  9]],

       [[ 4,  4, 11,  1],
        [19, 10, 16, 11],
        [10,  7, 15,  2],
        [ 7, 16,  1,  1],
        [ 4,  2, 18, 16]]], dtype=int32)

In [56]:
arr[1:, 0:2] = 5

In [57]:
arr[1:, 0:2]

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]], dtype=int32)

In [58]:
arr

array([[[16,  1, 14,  1],
        [11, 18,  1,  5],
        [ 2,  5, 15,  5],
        [10, 14, 19, 15],
        [19, 16,  3, 14]],

       [[ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [12,  5, 13, 19],
        [19, 11,  6,  1],
        [14, 17,  2,  9]],

       [[ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [10,  7, 15,  2],
        [ 7, 16,  1,  1],
        [ 4,  2, 18, 16]]], dtype=int32)

In [69]:
a = arr[-2:, -1:]

In [70]:
a

array([[[14, 17,  2,  9]],

       [[ 4,  2, 18, 16]]], dtype=int32)

In [71]:
a[0,-1] = 100

In [72]:
a

array([[[100, 100, 100, 100]],

       [[  4,   2,  18,  16]]], dtype=int32)

In [73]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [74]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
a = arr

In [76]:
b = arr.copy()

In [77]:
a[0][0]

np.int64(0)

In [78]:
a[0][0] = 50

In [79]:
a

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [80]:
b[0,0] 

np.int64(0)

In [81]:
b[0,0] = 100

In [82]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])