In [36]:
import numpy as np

### BroadCasting

In [2]:
arr = np.arange(0,9)
arr = arr.reshape(3,3)

In [3]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [5]:
arr-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [6]:
arr*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
arr+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
arr/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [9]:
a = np.array([1,2])
b = np.array([2,3])

In [10]:
a

array([1, 2])

In [11]:
b

array([2, 3])

In [12]:
a+b

array([3, 5])

In [13]:
a-b

array([-1, -1])

In [14]:
b-a

array([1, 1])

#### DOT product on 2 vector 


In [15]:
a = np.array([5, -3, 2])
b = np.array([4, 5, 3])

In [16]:
a

array([ 5, -3,  2])

In [17]:
b

array([4, 5, 3])

##### Isme dot se dono array ke numbers apse multiply and + ho jate h 5x4 + -3x5 + 2x3

In [18]:
a.dot(b) 

np.int64(11)

#### CROS prodcut 2 vectore

In [19]:
a = np.array([3,4,5])
b = np.array([7,8,9])

In [20]:
a

array([3, 4, 5])

In [21]:
b

array([7, 8, 9])

In [22]:
c = np.cross(a,b)

In [23]:
c

array([-4,  8, -4])

In [24]:
c.dot(a)

np.int64(0)

In [25]:
c.dot(a)

np.int64(0)

#### Determinant

In [26]:
arr = np.array([
    [3,5,2],
    [1,4,7],
    [6,8,9]
])

In [27]:
arr

array([[3, 5, 2],
       [1, 4, 7],
       [6, 8, 9]])

In [28]:
np.linalg.det(arr)

np.float64(72.99999999999999)

In [31]:
arr = np.array([
    [3,5,2],
    [6,10,4],
    [6,8,9]
])

In [32]:
arr

array([[ 3,  5,  2],
       [ 6, 10,  4],
       [ 6,  8,  9]])

In [33]:
np.linalg.det(arr)

np.float64(0.0)

#### Inverse matrix
##### An inverse matrix is a matrix that, when multiplied with the original matrix, yields the identity matrix. This concept only applies to square matrices (i.e., matrices with the same number of rows and columns) that are invertible (i.e., have a non-zero determinant).

In [8]:
arr = np.array([
    [1,2,3],
    [3,-2,1],
    [4,1,1]
    
])

In [9]:
inv = np.linalg.inv(arr)

In [10]:
inv

array([[-0.09375,  0.03125,  0.25   ],
       [ 0.03125, -0.34375,  0.25   ],
       [ 0.34375,  0.21875, -0.25   ]])

In [11]:
arr.dot(inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###### identiy matrix ka determiner nikala
###### i use for making identity matrix 

In [16]:
i = np.eye(3) 

In [14]:
np.linalg.det(i)

np.float64(1.0)

#### multiplication of 2 matrix

In [17]:
x  = np.random.randint(1,10,(3,3))

In [18]:
x

array([[6, 1, 2],
       [2, 1, 2],
       [3, 4, 2]], dtype=int32)

In [19]:
y = np.random.randint(1,10,(3,3))

In [20]:
y

array([[7, 7, 9],
       [8, 2, 1],
       [9, 5, 7]], dtype=int32)

###### this helps to multiply 2 matrix

In [21]:
x.dot(y)

array([[68, 54, 69],
       [40, 26, 33],
       [71, 39, 45]], dtype=int32)

#### Solving Linear Algebra

In [37]:
arr = np.array([
    [1,3,-2],
    [2,-1,6],
    [1,1,-2]
])

In [24]:
c = np.array([10,3,5])

In [25]:
inv = np.linalg.inv(arr)

In [26]:
inv

array([[-2.00000000e-01,  2.00000000e-01,  8.00000000e-01],
       [ 5.00000000e-01, -1.18952467e-17, -5.00000000e-01],
       [ 1.50000000e-01,  1.00000000e-01, -3.50000000e-01]])

In [31]:
inv.dot(c)

array([2.6 , 2.5 , 0.05])

#### Eigen Values Eigen Vectors

In [38]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [40]:
a,b = np.linalg.eig(arr)

In [41]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([ 3.25878567, -1.74822811, -3.51055757]), eigenvectors=array([[-0.68032035, -0.68273056,  0.58984922],
       [-0.685363  ,  0.71750056, -0.79590801],
       [-0.25969557,  0.13810117,  0.13641241]]))

In [42]:
a

array([ 3.25878567, -1.74822811, -3.51055757])

In [43]:
b

array([[-0.68032035, -0.68273056,  0.58984922],
       [-0.685363  ,  0.71750056, -0.79590801],
       [-0.25969557,  0.13810117,  0.13641241]])

#### Basic functions

In [44]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [45]:
np.sum(arr)

np.int64(9)

In [46]:
np.mean(arr)

np.float64(1.0)

In [47]:
np.median(arr)

np.float64(1.0)

In [49]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [52]:
np.argmin(arr) ## yeh bta raha h konse no. me min no. hai

np.int64(2)

In [53]:
np.min(arr)

np.int64(-2)

In [54]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [55]:
np.argmax(arr)

np.int64(5)

In [56]:
np.max(arr)

np.int64(6)